services:
  - type: web
    name: equip-backend
    env: java
    buildCommand: ./equip/mvnw clean package -DskipTests
    startCommand: java -jar ./equip/target/equip-0.0.1-SNAPSHOT.jar
    plan: free
